server:
  port: 8082

spring:
  redis:
      host: localhost
      port: 6379
      password:
      timeout: 5000ms
      database: 0
      lettuce :
        pool :
          max-active: 200
          max-idle: 20
          max-wait: -1ms
          min-idle: 10
          time-between-eviction-runs: 60s


ldj:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c40199800a91f9314b
      accountToken: 2d0ac2668bbf4be585a112131604957a
      appId: 2c94811c9860a9c40199800a93793152
      templateId: 1

