server:
  port: 8082


team:
  leader: "ldj"
  phone: "12345678901"
  age: 2
  createTime: "2019-05-01"

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  mail:
    host: smtp.qq.com
    username: 381249925@qq.com
    password: xfszkpzivnhgbgfi #授权码
    properties.mail.smtp.ssl.enable: true

custom:
  qrcode:
    content: "http://www.baidu.com"


